# Getting started with Numpy and Matplotlib

------------------------------------------------------

*Pablo M. Olmos olmos@tsc.uc3m.es*

*Vanessa Gómez Verdejo vanessa@tsc.uc3m.es*

*Harold Molina Bulla h.molina@tsc.uc3m.es*

*Angel Navia Vázquez navia@ing.uc3m.es*

------------------------------------------------------

Notebook Version:

    * 1.0 (January 2019) Original Release
    * 1.1 (January 2020) More material included, inspired from the Python introduction by Jerónimo Arenas García (jeronimo.arenas@uc3m.es), Jesús Cid Sueiro (jcid@tsc.uc3m.es), Vanessa Gómez Verdejo (vanessa@tsc.uc3m.es), Óscar García Hinde (oghinnde@tsc.uc3m.es), Simón Roca Sotelo (sroca@tsc.uc3m.es)
    * 1.2 (September 2020) More on Matplotlib. Bar plots, contour plots etc ...
    * 1.3 (January 2025) Revised and updated version
    

[**Numerical Python, NUMPY**](http://www.numpy.org/) is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data, since arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Lets load the library and start with some examples.

In [ ]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)}) #To set the number of printed decimals to 3

## Creating Arrays

Numpy is a python library that lets you work with data vectors and matrices (we will call them numpy arrays) and directly apply operations over these arrays without the need to operate element by element.

Numpy arrays can be defined directly using methods such as `np.arange()`, `np.ones()`, `np.zeros()`, `np.eye()`, as well as random number generators. Alternatively, you can easily generate them from python lists (or lists of lists) containing elements of a numerical type by using `np.array(my_list)`.


### adimensional arrays (vectors)

In [ ]:
v1=np.array([2,4,6]) #The default type is int32 or int64 since we did not use any decimal point

print("The type of v1: ", v1.dtype)

v2=np.array([2.0,4.0,6.0])

print("The type of v2: ", v2.dtype)

v3=np.array([2,4,6],dtype=np.float32)

print("The type of v1: ", v3.dtype)

print(v1)

The array we just created is a **vector** or **1-dimensional** array, it is characterized by a single dimension: (Note the empty second entry when we call the method `.shape()`)

In [ ]:
print(v1.shape)

print(v1[2])

# Now we transform v1 into a 2 dimensional array (a matrix with a single column)
v1 = np.reshape(v1,[v1.shape[0],1])

print(v1.shape)

More examples with useful functions ...

In [ ]:

# The arange() function generates vectors of equally spaced numbers. We can
# specify start and stop positions as well as the step length (the steps don't
# need to be integers!):
print('A vector that goes from 2 to 8 in steps of 2: ', np.arange(2, 9, 2))

# Numpy also has a linspace() function that works exactly like its Matlab
# counterpart:
print('\nA vector of length 5 that spans from 0 to 1 in constant increments:\n',
      np.linspace(0, 1, 5))

# Notice the difference in the last number of the range.
# In arange, the last number does not enter the array, but in linspace by default the last name enters the array

We can also convert a numpy array or matrix into a python list with the method `np.tolist()`.

In [ ]:
my_array = np.arange(9).reshape((3, 3))
print(my_array)
print('the type is: ', type(my_array))

# Convert my_array to list

my_array_list =  my_array.tolist()
print('\n', my_array_list)
print('the type is: ',type(my_array_list))

## Arrays (matrices or tensors)

To correctly operate with numpy arrays we have to be aware of their dimensions. Are these two arrays  equal?

In [ ]:
array1 = np.array([1,1,1])
print('array1:\n', array1)

array2 = np.ones((3,1))
print('\narray2:\n', array2)

The answer is **no**. We can easily check this by examining their shapes and dimensions:

In [ ]:
print('Shape of array1 :',array1.shape)
print('Number of dimensions of array1 :',array1.ndim)
print('Shape of array2 :',array2.shape)
print('Number of dimensions of array2 :',array2.ndim)

Effectively, `array1` is a 1D array, whereas `array2` is a 2D  array.  There are some methods that will let you modify the dimensions of an array. To go from a 2-D to 1-D array we have the methods `flatten()`, `ravel()` and `reshape()`. Check the result of the following code (you can use the help function to check the funcionalities of each method).

In [ ]:
x1 = np.arange(9).reshape((3, 3))
print('x1:\n', x1)
print('Its shape is: ', x1.shape)

print('\n Using the method flatten:')
print('x1.flatten(): ', x1.flatten())
print('Its shape is: ', x1.flatten().shape)

print('\n Using the method ravel:')
print('x1.ravel(): ', x1.ravel())
print('Its shape is:', x1.ravel().shape)

print('\n Using the method reshape:')
print('x1.reshape(-1): ', x1.reshape(-1))
print('Its shape is: ', x1.reshape(-1).shape)


# Note that here the method reshape is used to reorganize the array into a 1-D
# array. A more common use of reshape() is to simply redimension an array from
# shape (i, j) to shape (i', j') satisfying the condition i*j = i'*j'.
# For example:
print('\n A more common use of reshape():')
x1 = np.arange(12).reshape((4, 3))
print('x1:\n', x1)
print('Its shape is: ', x1.shape)

print('\nx1.reshape((2,6)):\n', x1.reshape((2,6)))
print('Its shape is: ', x1.reshape((2,6)).shape)

Note: `flatten()` always returns a copy of the original vector, whereas `ravel()` and `shape()` returns a view of the original array whenever possible.

Sometimes we need to add a new dimension to an array, for example to turn a  1-D array into a 2-D column vector. For this we use `np.newaxis`.

In [ ]:
# Let's start with a 1-D array:
array1 = np.array([1,1,1])
print('1D array:\n',array1)
print('Its shape is: ', array1.shape)

# Let's turn it into a column vector (2-D array with dimension 1x3):
array2 = array1[:,np.newaxis]
print('\n2D array:\n',array2)
print('Its shape is: ', array2.shape)

# Let's turn it into a row vector (2-D array with dimension 3x1):
array3 = array1[np.newaxis,:]
print('\n2D array:\n',array3)
print('Its shape is: ', array3.shape)

We might also need to remove empty or unused dimensions. For this we have `np.squeeze()`:

In [ ]:
array1_1D = np.squeeze(array1)
print('1D array:\n',array1_1D)
print('Its shape is: ', array1_1D.shape)

array2_1D = np.squeeze(array2)
print('\n1D array:\n',array2_1D)
print('Its shape is: ', array2_1D.shape)

array3_1D = np.squeeze(array3)
print('\n1D array:\n',array3_1D)
print('Its shape is: ', array3_1D.shape)

We can create matrices where all elements are drawn from an iid normal distribution ...

In [ ]:
m1=np.random.rand(3,5)

print ("m1=%r \n\n is a matrix, where each elemet is iid sampled from a standard normal distribution. Its size is %r" %(m1,m1.shape))

In [ ]:
m1.shape

We can create tensors (matrices with more than 2 dimensiones). In this example B is a tensor where the first dimension spans three different 2x2 matrices.

In [ ]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])

print(B)
print("Dimension of B: ", np.ndim(B))
print(np.shape(B))

## Indexing and slicing


Remember that the first element is indexed by 0 ...

In [ ]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
# print the first element of F, i.e. the element with the index 0
print(F[0])
# print the last element of F
print(F[-1])

In [ ]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B)
print(B[0,1,0])

### Slicing

In numpy, slicing means selecting and/or accessing specific array rows and columns.

Particular elements of numpy arrays (both unidimensional and multidimensional) can be accessed using standard python slicing. When working with multidimensional arrays, slicing can be carried out along several different dimensions at once.

In [ ]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[0:4])
print(S[:4])
print(S[6:])
print(S[:])
print(S[-2:])
print(S[:-3])

In [ ]:
A = np.array([
[11,12,13,14,15],
[21,22,23,24,25],
[31,32,33,34,35],
[41,42,43,44,45],
[51,52,53,54,55]])
print("")
print(A)
print("")
print(A[:3,2:])
print("")
print(A[3:,:])
print("")
print(A[:,4:])

We have seen how slicing allows us to index over the different dimensions of a given array. In the previous examples we learned how to select the rows and columns we're interested in, but how can we select only the elements of an array that meet a specific condition?

Numpy provides us with the method `np.where(condition)`. A common way of using this function is by setting a condition involving an array. For example, the condition x > 5 will give us the indexes in which x contains numbers higher than 5.

In [ ]:
x = np.array([-3,-2,-1,0,1,2,3])

# Create a new vector `y` with the elements of x, but replacing by 0 each number whose
# absolute value is 2 or less.

y = np.copy(x) # CAUTION! Doing y = x will create two pointers to the same array.
condition = np.abs(x)<=2
y[np.where(condition)[0]]=0
# Note that np.where() returns a tuple. In this case the second element of the
# tuple is empty. Read the np.where() docstring for more info.

print('Before conditioning: \n',x)
print('\nAfter conditioning: \n',y)

Note that the following indexing is also valid, but the result is different from what we get when using `np.where()`

In [ ]:
print(x[condition])

## Concatenating arrays

Provided that the corresponding dimensions fit, horizontal and vertical stacking of matrices can be carried out with methods `np.hstack()` and `np.vstack()`.

> **Exercise**: Complete the following exercises to practice matrix concatenation:

In [ ]:
my_array = np.array([[1, -1, 3, 3],[2, 2, 4, 6]])
print('Array 1:')
print(my_array)
print(my_array.shape)

my_array2 = np.ones((2,3))
print('Array 2:')
print(my_array2)
print(my_array2.shape)


# Vertically stack matrix my_array with itself
ex1_res = #YOUR CODE HERE
print('Vertically stack:')
print(ex1_res)

# Horizontally stack matrix my_array and my_array2
ex2_res = #YOUR CODE HERE
print('Horizontally stack:')
print(ex2_res)

# Transpose the vector `my_array`, and then stack a ones vector
# as the first column. Alternatively, you can stack a row, and then transpose.
# Just make sure that the final shape is (4,3). Name it `expanded`:

ones_v = #YOUR CODE HERE
expanded = #YOUR CODE HERE

print('Expanded array: \n',expanded)
print('Its shape is: \n', expanded.shape)

The output should be:

```
Array 1:
[[ 1 -1  3  3]
 [ 2  2  4  6]]
(2, 4)
Array 2:
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
Vertically stack:
[[ 1 -1  3  3]
 [ 2  2  4  6]
 [ 1 -1  3  3]
 [ 2  2  4  6]]
Horizontally stack:
[[ 1. -1.  3.  3.  1.  1.  1.]
 [ 2.  2.  4.  6.  1.  1.  1.]]
Expanded array:
 [[ 1.  1.  2.]
 [ 1. -1.  2.]
 [ 1.  3.  4.]
 [ 1.  3.  6.]]
Its shape is:
 (4, 3)
 ```

## Some operations with arrays

### Element-wise operations

We can perform all the usual numerical and matrix operations with numpy. In the case of matrix addition and subtraction, we can use the common "`+`" or "`-`" operators.

In [ ]:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3))
result = x1 + x2
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nAddition of x1 and x2 using the + operator:\n', result)

However, numpy provides us with built-in functions that guarantee that any errors and exceptions are handled properly:

In [ ]:
# We can add two arrays:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3))
result = np.add(x1, x2)
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nAddition of x1 and x2 using built-in functions:\n', result)

# Or compute the difference:
result = np.subtract(x1, x2)
print('\nSubtraction of x1 and x2 using built-in functions:\n', result)

We can also add or subtract column or row vectors from arrays. Again, both the basic operators and the built in functions will perform the same operations. Unlike in Matlab, where this operation will raise an error, Python will automatically execute it row by row or column by column as appropriate:

In [ ]:
# We can add or subtract row and column vectors:
row_vect = np.ones((1, 3))
col_vect = np.ones((3, 1))
result = np.add(x1, row_vect)
print('x1:\n', x1, '\n\nrow_vect:\n', row_vect, '\n\ncol_vect:\n', col_vect)
print('\nAddition of a row vector:\n', result)
result = np.add(x1, col_vect)
print('\nAddition of a column vector:\n', result)

Another key difference with Matlab is that the "`*`" operator won't give us matrix multiplication. It will instead compute an element-wise multiplication. Again, numpy has a built-in function for this purpose that will guarantee propper handling of errors:

In [ ]:
# We can perform element-wise multiplication by using the * operator:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3)) * 2 # a 3x3 array with 2s in every cell
result = x1 * x2
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nElement-wise multiplication of x1 and x2 using the * operator:\n', result)

# or by using the built-in numpy function:
result = np.multiply(x1, x2)
print('\nElement-wise multiplication of x1 and x2 using built-in functions:\n', result)


Some other useful element-wise operators ...

In [ ]:
#Elementwise operations over vector and matrices ...

M=np.random.randint(2,10,m1.shape)

print (M)

#We can use the "`**`" operator or the `power()` built-in function
#to raise elements from a matrix to a given power,
#or to raise elements of one matrix to
#positionally-corresponding powers in another matrix:

print (M**2) #square each element of m3

#Element-wise division between matrices is performed using the
#''`/`'' operator or the  `divide()` built-in function
print(M/M)

print(np.log(M))

print(np.exp(M))

## Matrix multiplication, inversion and pseudo-inverse

Numpy also gives us funtions to perform matrix multiplications and dot products. The `np.dot()` function is very powerful and can perform a number of different operations depending on the nature of the input arguments. For example, if we give it a pair of matrices of adequate dimensions, it will perform the same operation as `np.matmul()`.

In [ ]:
x1 = np.arange(9).reshape((3, 3))
x2 = np.ones((3, 3)) * 2 # a 3x3 array with 2s in every cell
result = np.matmul(x1, x2)
print('x1:\n', x1, '\n\nx2:\n', x2)
print('\nProduct of x1 and x2 using np.matmul():\n', result)

result = np.dot(x1, x2)
print('\nProduct of x1 and x2 using np.dot():\n', result, '\n')

# Read the np.dot() documentation for more information:
help(np.dot)

Finally, we can transpose a matrix by using the `numpy.transpose()` function, the `ndarray.transpose()` method or its abbreviated version, `ndarray.T`. We usually use the abbreviated version, but the other forms have their place in certain contexts. Check their documentations to see what options they offer:

In [ ]:
# Three different ways of transposing a matrix:
x1 = np.arange(9).reshape((3, 3))
print('x1:\n', x1)
print('\nTranspose of x1 using the numpy function:\n', np.transpose(x1))
print('\nTranspose of x1 using the ndarray method:\n', x1.transpose())
print('\nTranspose of x1 using the abbreviated form:\n', x1.T)
print('\nOddly enough, the three methods produce the same result!')

In python 3.X, `np.dot` can  be replaced by `@`

In [ ]:
M = np.random.randn(3,4)

M2=np.dot(M, M.transpose()) #We have to transpose to be able to multiply the matrices.

print(M2 -(M @ M.transpose()))

### Determinant and matrix inversion

In [ ]:
print('The determinant of M2 is %r' %(np.linalg.det(M2)))

M2I = np.linalg.pinv(M2)

print(M2 @ M2I)

In mathematics, and in particular linear algebra, **a pseudoinverse** $A^+$ of a matrix $A$ is a generalization of the inverse matrix. The most widely known type of matrix pseudoinverse is the [Moore–Penrose inverse](http://mathworld.wolfram.com/Moore-PenroseMatrixInverse.html).

When $A$ has linearly independent rows, i.e. $AA^*$ is invertible where $A^*$ is the Hermitian transpose, then the Pseudo-inverse $A^+$ can be computed as follows:

$$ A^+ = A^* (AA^*)^{-1} $$

and it verifies that $AA^+ =I$.


In [ ]:
M2PSI = np.linalg.pinv(M)

print(M @ M2PSI)
print('\n')

print(np.trace(M @ M2PSI))
print('\n')

print(np.trace(M @ M2PSI)-np.sum(M @ M2PSI)) # Sum of out diagonal elements
print('\n')

print(np.dot(M, M2PSI))



## Some useful functions to create arrays

In [ ]:
v = np.linspace(-3,5,20) # 20 elements equally spaced in the -3,5 range

print(v)
print("")

v2 = np.logspace(0,10,10) # 10 elements equally spaced in the 10^0,10^10 range

print(v2)
print("")


v3 = np.arange(-3,5,0.5)

print(v3)
print("")




## Saving data using the pickle package

The [pickle module](https://docs.python.org/2/library/pickle.html) implements a fundamental, but powerful algorithm for serializing and de-serializing a Python object structure. Essentially, it converts all objects you want to save into a text file.


To save data into a pickle file, we will create a dictionary will all fields we want to save.


In [ ]:
import pickle

save_data = {'v1': v1, 'v2': v2, 'v3':v3} #v1,v2,v3 are defined above

with open('my_pick_file.pickle', 'wb') as handle:
    pickle.dump(save_data, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('my_pick_file.pickle', 'rb') as handle:
    load_data = pickle.load(handle)

print(save_data['v1'])
print(load_data['v1'])

# Matplotlib

[Matplotlib](https://matplotlib.org/) is a Python 2D plotting library which produces figures in a variety of formats. Matplotlib can be used in Python scripts, the Python and IPython shells, the Jupyter notebook, and web application servers.

Matplotlib tries to make easy things easy and hard things possible. You can generate plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc., with just a few lines of code. For examples, see the sample plots and thumbnail gallery.

For simple plotting the pyplot module provides a MATLAB-like interface, particularly when combined with IPython. For the power user, you have full control of line styles, font properties, axes properties, etc, via an object oriented interface or via a set of functions familiar to MATLAB users.


In [ ]:
import matplotlib.pyplot as plt
#The following is required to print the plots inside the notebooks
%matplotlib inline
%config InlineBackend.figure_format = 'retina' #High quality figures

###  Data generation

In python, random samples can be easily generated with the `numpy.random` package. Inside it we can find many usefull tools to sample from the most important probability distributions.

We have common number generator functions:
* `rand()`: uniformily generates random samples.
* `randn()`: returns samples from the “standard normal” distribution.

Or more specific ones:
* `exponential([scale, size])`: draw samples from an exponential distribution with a given scale parameter.
* `normal([loc, scale, size])`:	draw random samples from a normal (Gaussian) distribution with parameters: loc (mean) and scale (standard deviation).
* `uniform([low, high, size])`: draw samples from a uniform distribution in the range low-high.

In the following examples we will look at different random generation methods and we will visualize the results. For the time being, you can ignore the visualization code. Later on we will learn how these visualization tools work.



In [ ]:
# Random samplig examples
n = 1000 # number of samples

# Sampling from a standard uniform distribution:
x_unif = np.random.rand(n)

fig1 = plt.figure()
plt.hist(x_unif, bins=100)
plt.title('Samples from a uniform distribution between 0 and 1')
plt.grid()
plt.show()

# Sampling from a normal distribution:
x_norm = np.random.randn(n)

fig2 = plt.figure()
plt.hist(x_norm, bins=100)
plt.title('Samples from a normal distribution with 0 mean and unity variance')
plt.grid()
plt.show()

# Adding Gaussian noise to a linear function:
n = 30
x = np.linspace(-5, 5, n)
noise = np.random.randn(n)
y = 3*x
y_noise = y + noise

fig3 = plt.figure()
plt.plot(x, y, color='black', linestyle='--', label='Clean signal')
plt.plot(x, y_noise, color='red', label='Noisy signal')
plt.legend(loc=4, fontsize='large')
plt.title('Visualization of a noisy data-set')
plt.grid()
plt.show()

More about plotting with `matplotlib`

In [ ]:
t = np.arange(0.0, 1.0, 0.05) # Time vector, from 0s to 1s in steps of 0.05s.
a1 = np.sin(2*np.pi*t) # Samples of the first signal.
a2 = np.sin(4*np.pi*t) # Samples of the second signal.

# Visualization

# We can create a figure that will contain our plots.
plt.figure()
# We can plot the two signals in different subplots, as in Matlab.

# First signal
ax1 = plt.subplot(211)
ax1.plot(t,a1)
plt.title('First sinusoid.')
plt.xlabel('t (seconds)')
plt.ylabel('a_1(t)')

# Second signal
ax2 = plt.subplot(212)
ax2.plot(t,a2, 'r.')
plt.title('Second sinusoid.')
plt.xlabel('t (seconds)')
plt.ylabel('a_2(t)')

# We ensure the two plots won't overlap, and finally we show the results on the
# screen.
plt.tight_layout()
plt.show()

Let's analyse how we have created the previous figures and in which things they differ:



*   A crucial aspect to consider is that **both curves represent a set of discrete samples** (the samples we've generated). While the second plot uses red dots to represent the data (specified through `'r.'`), the first one will draw the points using the standard blue line. As in Matlab, using lines to plot samples will interpolate them by default. If we don't want Matplotlib to do so, we can specify a different symbol, like dots, squares, etc...
*   We can label the axis and set titles, enhancing the way in which our data is presented. Moreover, we can improve the clarity of a figure by including or modyfing the line width, colours, symbols, legends, and a big etcetera.

Look at the following figure and try to catch which argument and/or piece of code is related with each feature. It's intuitive! You can modify the parameters and see what's the new outcome.


In [ ]:
t = np.arange(0.0, 3, 0.05)
a1 = np.sin(2*np.pi*t)+t
a2 = np.ones(a1.shape)*t

plt.figure()
# We are going to plot two signals in the same figure. For each one we can
# specify colors, symbols, width, and the label to be displayed in a legend.
# Use the Matplotlib docs if you want to know all the things you can do.
plt.plot(t,a1,'r--',linewidth=2, label='Sinusoidal')
plt.plot(t,a2, 'k:', label='Straight Line')


plt.title('Playing with different parameters')
plt.ylabel('Amplitude')
plt.xlabel('Time (seconds)')

# By default, axis limits will coincide with the highest/lowest values in our
# vectors. However, we can specify ranges for x and y.
plt.xlim((-0.5, 3))
plt.ylim((-0.5, 4))

# When plotting more than one curve in a single figure, having a legend is a
# good practice. You can ask Matplotlib to place it in the "best" position
# (trying not to overlap the lines), or you can specify positions like
# "upper left", "lower right"... check the docs!
plt.legend(loc='best')

# We can draw the origin lines, to separate the bidimensional space in four
# quadrants.
plt.axhline(0,color='black')
plt.axvline(0, color='black')

# We can also set a grid with different styles...
plt.grid(color='grey', linestyle='--', linewidth=0.8)

# And specify the "ticks", i.e., the values which are going to be specified in
# the axis, where the grid method is placing lines.
plt.xticks(np.arange(-0.5, 3, 0.5)) # In x, put a value each 0.5.
plt.yticks(np.arange(-0.5, 4, 1)) # In y, put a value each 1.

# Finally, plot all the previous elements.
plt.show()


In just a single example we have seen a lot of Matplotlib functionalities that can be easely tuned. You have all you need to draw decent figures. However, those of you who want to learn more about Matplotlib can take a look at [AnatomyOfMatplotlib](https://github.com/matplotlib/AnatomyOfMatplotlib), a collection of notebooks in which you will explore more in depth Matplotlib.

Consider `x` a vector containing samples coming from a 1-dimensional random variable. A histogram is a figure in which we represent the observed frequencies of different ranges of the `x` domain. We can express them as relative frequencies (summing up to 1) or absolute frequencies (counting events).

We can adapt the number and size of intervals (called bins) to directly affect the resolution of the plot.

When we have a sufficiently high number of random samples coming from the same distribution, its histogram is expected to have a similar shape to the theoretical expression corresponding to the density of this distribution.

In Matplotlib, we have already plotted histograms, with `plt.hist(samples,bins=)`.

Let's see some examples:

In [ ]:
# We take samples from a normalized gaussian distribution, and we change
# mean and variance with an operation.
sigma = 4
mn = 5
x_norm = mn + np.sqrt(sigma)*np.random.randn(5000)

# Let's obtain an histogram with high resultion, that is, a lot of bins.
fig1 = plt.figure()
plt.hist(x_norm, bins=100,label='Samples')
plt.title('Histogram with 100 bins')

# With vertical lines, we plot the mean and the intervals obtain summing one
# standard deviation to the mean.
plt.axvline(x=np.mean(x_norm),color='k',linestyle='--',label='Mean')
plt.axvline(x=np.mean(x_norm)+np.std(x_norm),color='grey',linestyle='--',label='Mean +/- std')
plt.axvline(x=np.mean(x_norm)-np.std(x_norm),color='grey',linestyle='--')


plt.legend(loc='best')
plt.show()

# We check that the mean and variance of the samples is aprox. the original one.
print('Sample mean = ', x_norm.mean())
print('Sample variance = ', x_norm.var())

# Now let's plot a low resolution histogram, with just a few bins.
fig2 = plt.figure()

# We can set weights in this way to obtain a normalized histogram, i.e.,
# expressing relative frequencies.
w_n = np.zeros_like(x_norm) + 1. / x_norm.size

plt.hist(x_norm, bins=10,label='Samples',weights=w_n)
plt.title('Histogram with 10 bins')
plt.axvline(x=np.mean(x_norm),color='k',linestyle='--',label='Mean')
plt.axvline(x=np.mean(x_norm)+np.std(x_norm),color='grey',linestyle='--',label='Mean +/- std')
plt.axvline(x=np.mean(x_norm)-np.std(x_norm),color='grey',linestyle='--')
plt.legend(loc='best')
plt.show()

# A different resolution leads to different representations, but don't forget
# that we are plotting the same samples.

print('Sample mean = ', x_norm.mean())
print('Sample variance = ', x_norm.var())


### More examples: Bar plot

The following code represents a bar plot with some predefined labels ...


In [ ]:
labels = ['A','B','C','D','E','F','G']
values = np.array([1,2,5,8,5,1,0])

width = 0.35  # Bar width

x = np.arange(len(labels))

fig, ax = plt.subplots()
rect = ax.bar(x, values, width=width)
plt.grid(which='major', color='gray', alpha=0.6, linestyle='dotted', lw=1.5)
plt.xticks(x,labels)
plt.ylabel('Values')
plt.title('A bar plot')
plt.show()


### More examples: array of plots and text over figures

You can easily create arrays of plots to visualize them together. Here's an example. Also, we show how to include anotations in the figures.

In [ ]:
def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)

t1 = np.arange(0.0, 5.0, 0.1)
t2 = np.arange(0.0, 5.0, 0.02)

plt.figure()
plt.subplot(211)
plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')
num_figure = 1
plt.annotate('local max', xy=(1, f(1)), xytext=(1.25, 0.85),
             arrowprops=dict(facecolor='red', width = 1))
plt.text(4, 0.75, "Figura {0:d}".format(num_figure))
plt.grid()

plt.subplot(212)
plt.plot(t2, np.cos(2*np.pi*t2), 'r--')

plt.text(6, 0, "Figure {0:d}".format(num_figure+1), style='italic',
        bbox={'facecolor': 'blue', 'alpha': 0.5, 'pad': 10})
plt.grid()
plt.show()

### More examples: contour and surface plots

These plots are handy to represent functions over 2 dimensional spaces.


In [ ]:
# We consider the following function with 2D inputs

def f(x,y):
    return np.exp((+x**2-y**2+x*y+x-y)/20)

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

# Lets start with a contour plot

grid_points = 100
lims = 4
# Grid of grid_points**2 points in the [-2,2] square
x,y = np.mgrid[-lims:lims:2*lims/grid_points, -lims:lims:2*lims/grid_points]
grid = np.transpose(np.row_stack([x.ravel(), y.ravel()]))

# Lets evaluate the function over the grid

f_grid = f(grid[:,0],grid[:,1]).reshape([grid_points,grid_points])

fig = plt.figure(figsize=(6, 18))

# Contour lines
plt.subplot(311)
plt.contour(x,y,f_grid,np.arange(0,1,0.05),cmap='coolwarm') # We plot the 0, 0.1, 0.2, ..., 1.0 contour lines
plt.colorbar()
plt.grid()
plt.title("Contour lines")

# Contour plot
plt.subplot(312)
plt.contourf(x,y,f_grid,cmap='coolwarm')
plt.colorbar()
plt.grid()
plt.title("Contour plot")

# Surface plot
ax = fig.add_subplot(3, 1, 3, projection='3d')
ax.plot_surface(x,y,f_grid,cmap='coolwarm')
plt.colorbar()
plt.grid()
plt.title("Surface plot")

plt.show()

